### ISSUE TITLE
Permission to Distribute

### ISSUE THREAD

**Issue by mjbrowns** [BrettSheleski/comchap#18]
I've been working on a docker service that combines plex and comskip (and a few other things) to produce a simple to use plex implementation complete with automatic commercial marking/cutting and transcoding.

I've published my build files on github [here](http://github.com/mjbrowns/plexpost).

I've been using (unmodified) your *comchap* and *comcut* scripts.  

What I provide at this point is a dockerfile and a set of scripts that will build a container that includes comcut and comchap copied directly from your github repo.  What I'd really like to do is set up an automated build on the dockerhub for a complete container that includes a pre-built comskip.

Before I do that I wanted to make sure it was okay with you.  I'm not really sure what license you provide the source code, but I figure its best to make sure its okay with you before I proceed.

**Comment by BrettSheleski** [comment]
Sounds fine by me. I'd just like to add some sort of license to the top of the files before you'd package anything.

Also, I think it would be best if instead of packaging a copy of comcut and/or comchap in your code base, instead make a script that will pull the latest from my GitHub repo.

I've never messed with docker container stuff yet, but it seems interesting.

**Comment by BrettSheleski** [comment]
Added LICENSE.txt file (1a4604b).

Go ahead and distribute.
